<a href="https://colab.research.google.com/github/idreesibrahim9/Medical-Dataset/blob/main/pandas_medicaldataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [114]:
import pandas as pd

In [115]:
from google.colab import drive
drive.mount('content_drive')

Drive already mounted at content_drive; to attempt to forcibly remount, call drive.mount("content_drive", force_remount=True).

In [116]:
df=pd.read_csv("content_drive/MyDrive/medical_insurance.csv")

In [117]:
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
2767   47  female  45.320         1     no  southeast   8569.86180
2768   21  female  34.600         0     no  southwest   2020.17700
2769   19    male  26.030         1    yes  northwest  16450.89470
2770   23    male  18.715         0     no  northwest  21595.38229
2771   54    male  31.600         0     no  southwest   9850.43200

[2772 rows x 7 columns]

In [118]:
from sklearn.preprocessing import LabelEncoder

In [119]:
coder=LabelEncoder()

In [120]:
df["sex"] = df["sex"].astype(str)
df["sex"] = coder.fit_transform(df["sex"])

In [121]:
df["smoker"] = df["smoker"].astype(str)
df["smoker"] = coder.fit_transform(df["smoker"])

In [122]:
df["region"] = df["region"].astype(str)
df["region"] = coder.fit_transform(df["region"])

In [123]:
df["bmi"]=df["bmi"].astype(int)
df["charges"]=df["charges"].astype(int)

In [124]:
x=(df.drop("charges",axis=1))
y=df["charges"]

In [125]:
x

      age  sex  bmi  children  smoker  region
0      19    0   27         0       1       3
1      18    1   33         1       0       2
2      28    1   33         3       0       2
3      33    1   22         0       0       1
4      32    1   28         0       0       1
...   ...  ...  ...       ...     ...     ...
2767   47    0   45         1       0       2
2768   21    0   34         0       0       3
2769   19    1   26         1       1       1
2770   23    1   18         0       0       1
2771   54    1   31         0       0       3

[2772 rows x 6 columns]

In [126]:
y

0       16884
1        1725
2        4449
3       21984
4        3866
        ...
2767     8569
2768     2020
2769    16450
2770    21595
2771     9850
Name: charges, Length: 2772, dtype: int64

In [127]:
from sklearn.model_selection import train_test_split

In [128]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [129]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2217 entries, 2386 to 1817
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       2217 non-null   int64
 1   sex       2217 non-null   int64
 2   bmi       2217 non-null   int64
 3   children  2217 non-null   int64
 4   smoker    2217 non-null   int64
 5   region    2217 non-null   int64
dtypes: int64(6)
memory usage: 121.2 KB

In [130]:
x_test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 555 entries, 13 to 2000
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       555 non-null    int64
 1   sex       555 non-null    int64
 2   bmi       555 non-null    int64
 3   children  555 non-null    int64
 4   smoker    555 non-null    int64
 5   region    555 non-null    int64
dtypes: int64(6)
memory usage: 30.4 KB

In [131]:
y_train.info()

<class 'pandas.core.series.Series'>
Index: 2217 entries, 2386 to 1817
Series name: charges
Non-Null Count  Dtype
--------------  -----
2217 non-null   int64
dtypes: int64(1)
memory usage: 34.6 KB

In [132]:
y_test.info()

<class 'pandas.core.series.Series'>
Index: 555 entries, 13 to 2000
Series name: charges
Non-Null Count  Dtype
--------------  -----
555 non-null    int64
dtypes: int64(1)
memory usage: 8.7 KB

In [133]:
from sklearn.linear_model import LinearRegression

In [134]:
model=LinearRegression()

In [135]:
model.fit(x_train, y_train)

LinearRegression()

In [136]:
prediction = model.predict(x_test)

In [137]:
prediction

array([ 1.48935233e+04,  9.22793296e+03,  7.08704462e+03,  4.67900878e+03,
        3.08807017e+04,  8.39643491e+03,  8.49871124e+03,  1.60839873e+04,
        8.94381986e+03,  1.42952634e+04,  3.20182425e+04,  5.40623859e+03,
        2.86800510e+04,  3.71032297e+03,  1.48872042e+04,  6.39591618e+02,
        5.72507773e+03,  1.78748391e+02,  2.69402355e+04,  7.78595411e+03,
        2.50418950e+04,  1.16402658e+04,  1.25477729e+04,  1.53249727e+04,
        2.73761139e+04,  1.07282357e+04,  1.11186924e+04,  2.74313193e+04,
        1.85892939e+03,  1.03356207e+03,  1.57222161e+04,  2.95523009e+04,
        1.27360870e+04,  4.49000535e+03,  1.45501185e+04,  3.11614894e+04,
        2.82905363e+03,  3.78884402e+03,  5.47235043e+03,  2.98178741e+04,
        2.79199326e+04,  3.67434685e+03,  2.81446490e+04,  1.43684552e+04,
        7.56340626e+02,  7.38584108e+03,  4.44230939e+03,  9.68709989e+03,
        3.80717775e+04,  3.11739511e+04,  1.18452972e+04,  1.29525973e+04,
        8.58876673e+03,  9.45230657e+03,  5.43786521e+03,  3.60071466e+04,
        1.77293898e+04,  1.37275040e+04,  3.26477147e+04,  3.84594289e+04,
        1.56552908e+04,  1.57222161e+04,  5.72570277e+03,  1.36469195e+04,
        3.54689917e+04,  4.24354466e+03,  3.99512544e+03,  1.26555549e+04,
        8.16489842e+03,  1.08812512e+04,  1.13668294e+04,  9.85039674e+03,
        5.74148985e+03,  9.06027557e+03,  3.04079280e+04,  2.68352063e+04,
        1.14470711e+04,  1.04942892e+04,  9.94832357e+03,  1.08210936e+04,
        6.07254983e+03,  4.78928049e+03,  9.22305231e+03,  1.90456187e+03,
        1.47126019e+04,  1.45349564e+04,  1.20460729e+04,  1.84803033e+04,
        6.99158838e+03,  1.43672576e+04,  9.78066618e+03,  8.39730078e+03,
        4.36115508e+02,  1.36523202e+04,  2.87801471e+04,  1.50026197e+04,
        1.29567170e+04,  1.02322821e+03,  1.06866180e+04,  3.62239528e+03,
        1.85937764e+04,  7.18501288e+03,  2.50418950e+04,  1.01801423e+04,
        7.91492396e+03,  5.08739944e+03,  8.37663305e+03,  1.41035071e+04,
        1.86713545e+03,  9.06602208e+03,  7.44238000e+03,  6.18578506e+03,
        8.63806742e+03,  8.97683246e+03,  1.57270442e+04,  9.53425797e+03,
        4.54027764e+03,  1.06866180e+04,  6.87242125e+03,  3.20770142e+04,
        3.37345880e+04,  1.29300452e+03,  1.93400823e+03,  5.91884502e+03,
        1.06697371e+03,  1.77293898e+04,  1.19305740e+04,  1.02320414e+04,
        5.52836924e+03,  1.48872042e+04,  3.54254346e+04,  3.70760525e+04,
        1.99691869e+03,  1.29525973e+04,  3.38635578e+04,  1.61947075e+04,
        5.69965999e+02,  4.74732000e+03,  2.71725854e+04,  1.34589371e+04,
        3.62239528e+03,  7.58386397e+03,  1.22295063e+04,  3.57505404e+04,
        9.72745268e+03,  2.71355580e+04,  1.04279890e+04,  1.00465327e+04,
        1.07315611e+04,  1.04880226e+04,  6.22189708e+03,  1.21032369e+04,
        1.46380956e+04,  1.38501547e+04,  1.01651162e+04,  1.05411717e+04,
        5.66554514e+03,  3.14686087e+04,  3.48198345e+04,  3.99298863e+04,
        1.49979274e+04,  3.18500650e+04,  3.08755913e+04,  3.94916502e+04,
        1.32251789e+04,  9.06796152e+03,  1.46094102e+04,  4.54027764e+03,
        1.22316341e+04,  1.21851882e+04,  2.75048012e+03,  3.60071466e+04,
        3.18637243e+04,  5.91320344e+03,  6.12720177e+03,  2.84077347e+03,
        2.17702670e+03,  4.09240561e+04,  8.03442581e+03,  3.19008305e+03,
        7.41897047e+03,  5.05037206e+03,  9.06027557e+03,  2.90274736e+04,
        3.80717775e+04,  1.11931987e+04,  3.05907888e+04,  5.14191549e+03,
        8.25718367e+03,  1.09473630e+04,  1.38522825e+04,  5.66554514e+03,
        6.93315145e+03,  6.67212420e+03,  4.49000535e+03,  3.42243295e+03,
        1.45063205e+04,  1.74043365e+04,  3.54317537e+04,  9.21020643e+03,
        1.16603085e+04,  8.81324231e+03,  3.26366391e+04,  1.90456187e+03,
        1.34045260e+04,  1.56234344e+04,  8.39730078e+03,  3.72768282e+04,
        3.76771284e+02,  3.12199678e+04,  2.52240783e+04,  6.18114525e+03,
        1.33305923e+04,  5.57055951e+03,  9.96496547e+03,  1.28876115e+04,
        2.71369060e+03,  2.37780244e+03,  5.91339180e+03,  3.11326156e+04,
        1.67510595e+04,  3.28518159e+04,  8.66177024e+03,  3.33151457e+03,
        3.99298863e+04,  3.07005937e+04,  3.18742465e+04,  3.97521864e+03,
        2.69402355e+04,  1.98107915e+03,  2.12720294e+03,  1.32146567e+04,
        5.59321915e+03,  7.51636616e+03,  1.11668670e+04,  1.50322545e+04,
        9.06872245e+03,  1.38604886e+04,  1.14470711e+04,  7.85977101e+03,
        1.06135502e+04,  1.28173609e+04,  6.44419796e+02,  1.79068974e+03,
        5.02265447e+03,  1.16984124e+04,  7.72998777e+03,  1.47079096e+04,
        3.74044121e+04,  1.16603085e+04,  5.53927567e+03,  1.57776623e+04,
        3.76694127e+04,  3.71704130e+04,  3.41616633e+03,  3.36956707e+04,
        2.64100045e+04,  1.32119563e+04,  6.04918173e+03,  1.05177097e+04,
        1.16519666e+04,  3.30754811e+04,  6.48196457e+03,  2.89864285e+04,
        5.97560566e+03,  1.00443524e+04,  8.48630204e+03,  3.34101073e+04,
        1.61947075e+04,  1.69102700e+04,  1.20616716e+04,  4.87852258e+03,
        7.70950841e+03,  1.50322545e+04,  9.77371020e+03,  1.28282673e+04,
        1.10675018e+04,  5.33328755e+03,  1.47079096e+04,  5.24385710e+03,
        1.60560289e+04,  9.86343098e+03,  9.89443256e+03,  7.10959932e+03,
        8.39643491e+03,  4.78928049e+03,  1.11992769e+04,  5.32690414e+03,
        3.18127745e+04,  3.91236064e+03,  1.32119563e+04,  5.99804357e+03,
        1.05694205e+04,  2.50339440e+03,  1.07282357e+04,  4.38140993e+03,
        1.12117386e+04,  7.83307750e+03,  1.08833790e+04,  3.90060720e+04,
        1.03705842e+04,  2.18379432e+03,  3.87574762e+03,  1.73129305e+03,
        5.45656335e+03, -1.32509734e+02,  6.63359405e+03,  5.35302508e+03,
        8.16827630e+03,  6.63359405e+03,  2.65164196e+04,  3.51979654e+04,
        1.22833449e+04,  4.08916686e+04,  6.44585256e+03,  2.37467577e+02,
        3.90076485e+03,  1.36468670e+04,  1.21361779e+04,  9.20939303e+03,
        2.32328639e+03,  2.73761139e+04,  1.86306820e+03,  2.57582533e+03,
        1.35991067e+04,  4.11370895e+03,  8.81680855e+03,  5.18209475e+03,
        1.17251584e+04,  6.93171301e+03,  1.10560228e+04,  4.53109997e+03,
        1.20460729e+04,  3.18127745e+04,  9.46814612e+03,  9.96496547e+03,
        3.48935819e+03,  4.59333293e+03,  9.21214588e+03,  2.73685329e+04,
        7.18501288e+03,  1.01545939e+04,  3.62514813e+03,  3.04065420e+04,
        3.63879778e+04,  6.62871341e+03,  7.34847899e+03,  1.14048808e+04,
        2.77516263e+03,  1.16935843e+04,  3.65930616e+04,  3.69137795e+02,
        7.01529120e+03,  9.26955066e+03,  3.09729345e+04,  3.37732645e+04,
        9.89528739e+03,  4.97696952e+03,  9.33097022e+03,  2.83802063e+03,
        2.59464084e+04,  3.35329989e+04,  7.83365007e+03,  1.04886476e+04,
        1.16361795e+04,  1.61947075e+04,  1.07845973e+04,  1.22895924e+04,
        2.83509305e+04,  1.15876892e+04,  1.16984124e+04,  3.62541273e+04,
        1.54566953e+04,  4.54934957e+03,  8.97683246e+03,  3.54978655e+04,
        1.59072047e+04, -1.43243203e+03,  3.60385536e+03,  1.85937764e+04,
        5.74148985e+03,  1.19052140e+04,  4.12485621e+03,  1.42305184e+04,
        3.07287066e+04,  3.61969491e+03,  6.58477205e+03,  1.40430031e+03,
        1.05411717e+04,  1.17112583e+04,  1.30522257e+04, -1.17907969e+03,
        8.27870622e+03,  7.07314452e+03,  4.05253022e+03,  9.58075632e+03,
        1.22937312e+04,  3.42934520e+04,  5.30320132e+03,  7.00351890e+03,
        3.03396818e+03,  2.88805364e+04,  7.40858414e+03,  1.66349355e+04,
        8.87890562e+03,  4.10636876e+03,  1.40430031e+03,  7.72390951e+03,
        5.60355301e+03,  1.17264204e+04,  1.13434088e+04,  3.48397603e+04,
        3.18533904e+04,  4.01408075e+04,  1.49282494e+04,  1.02402475e+04,
        2.80853048e+04,  8.07219502e+03,  2.53661874e+04,  1.43977280e+04,
        2.73801287e+04,  3.29535008e+03,  4.46223528e+03,  2.46434568e+02,
        1.13836405e+04,  8.69253099e+03,  1.21701621e+04,  9.46814612e+03,
        1.55986994e+04,  9.46400731e+03,  3.71032297e+03,  3.89002294e+04,
        7.83307750e+03,  1.16361795e+04,  1.72859267e+03,  1.05694205e+04,
        3.48715977e+04,  1.65114714e+04,  3.37729822e+04,  1.27360870e+04,
        6.69525444e+03,  4.43886718e+03,  1.03577383e+04,  5.88567420e+03,
        1.54082576e+04,  1.36652186e+04,  3.39925277e+04,  3.20797145e+04,
        1.33865587e+04,  6.07254983e+03,  1.29416909e+04,  3.80331669e+03,
        6.05274797e+03,  5.64763026e+03,  2.52439327e+04,  1.22316341e+04,
        1.09439851e+04,  3.24455721e+04,  9.72745268e+03,  5.52492703e+03,
        1.43547959e+04,  8.93468360e+03,  3.30686610e+04,  3.11041389e+03,
        1.13856516e+04,  1.22246781e+04,  3.19129755e+04,  1.33838583e+04,
        1.80015774e+03,  5.46476941e+03, -4.16492931e+00,  1.13254939e+04,
        7.24103169e+03,  1.54226587e+04,  4.26827963e+03,  1.46307030e+04,
        1.04796997e+04,  5.21096853e+03,  7.31008474e+03,  1.48238452e+04,
        5.10048614e+03,  7.61129932e+03,  9.22305231e+03,  1.26158958e+04,
        1.03729004e+04,  2.86800510e+04,  9.88029461e+03,  7.32017777e+03,
        3.61728535e+04,  1.35991067e+04,  3.48163398e+04,  1.22950981e+04,
        9.89443256e+03,  3.02982813e+04,  2.80916239e+04,  1.69102700e+04,
        9.33779031e+03,  8.29850808e+03,  2.68352063e+04,  1.31471589e+04,
        8.32950966e+03, -7.86711947e+01,  1.14432256e+04,  4.46223528e+03,
        1.48851289e+04,  1.27020503e+04,  4.03726324e+03,  3.71580038e+04,
        4.07295712e+03,  1.72789329e+04,  1.13850265e+04,  3.04065420e+04,
        8.36354635e+03,  4.43886718e+03,  3.90559303e+03,  1.32091510e+04,
        4.08916686e+04,  6.09562761e+03,  3.03396818e+03,  7.21192812e+03,
        3.20100889e+04,  7.83302503e+03,  8.30614156e+03,  8.86661322e+03,
        5.83309760e+03,  1.85192094e+03,  1.21721015e+04,  1.02292886e+04,
        7.97778196e+03,  1.44476538e+04,  4.09240561e+04,  3.38483433e+04,
        1.25122335e+04,  1.08411362e+04,  1.13850790e+04,  2.71644344e+03,
        1.53249727e+04,  1.42952634e+04,  5.91614464e+03,  1.73129305e+03,
        3.22447964e+04,  6.30592381e+03,  3.43470625e+03,  7.61129932e+03,
        1.13385806e+04,  3.08807017e+04,  2.52855504e+04,  5.64763026e+03,
        2.28475625e+03,  3.01312075e+04,  3.16713430e+04,  1.46224969e+04,
        1.26378254e+04,  2.52418573e+04,  3.68255291e+03])

In [138]:
from sklearn.linear_model import LogisticRegression

In [139]:
model1=LogisticRegression()

In [140]:
model1.fit(x_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [141]:
prediction1 = model1.predict(x_test)

In [142]:
prediction1

array([13470, 36837, 13470,  6799, 14394, 37607,  8334, 13224,  7160,
       11743, 13470, 37607, 39611,  6238, 13143, 36837,  9432,  1242,
       30942,  6600, 36837, 12629, 12495, 12485, 39611, 14394, 11520,
       37465,  2304,  1826, 13887,  7160, 13224,  6059, 12495, 13470,
        4673, 37607,  8334, 13470,  6059, 26018, 37607, 13844, 13470,
        9101, 37465, 10096, 13470,  3925,  8334,  9866,  8965, 11658,
        1633, 47269, 13635, 13470,  4433, 47269, 11842, 13887, 13470,
       12485, 11743, 13470,  3597,  8965, 32108, 13844, 13470,  7160,
       13470, 13204, 36837,  8334, 12629, 24915,  3597,  9487,  5757,
        1633, 13470,  6799, 13470,  9101, 24915, 12495, 39611, 24915,
       13143,  2020,  1242,  9447,  8334, 15170,  7160,  1242, 13143,
        1639, 13470, 14449, 36837,  7160, 32108, 13470, 13470, 11842,
        1837, 47269, 14449,  1242,  4673, 36837, 13635,  7147, 14394,
       13143,  8615,  4673, 24915,  1708,  2395, 13470,  6059, 13635,
       10602, 12495, 19496, 13143,  8334, 28950,  2020,  9866, 47269,
        8334,  1837,  8334, 36837, 11743,  1639, 13844, 11842, 13470,
        7147,  8965,  7348,  5972, 14449, 10736, 12495, 11658, 10602,
       11743,  9447, 12233,  6600,  6799,  6985, 48517, 12495, 46718,
       39611, 47269, 37607,  7441,  9447, 14394,  9447, 10602,  6238,
       47269, 11743,  9850,  5757,  2203, 13470, 13470,  7147, 12495,
       26018,  6985, 13204, 35595, 13470,  6985, 13470,  7348,  4673,
        9850, 32108,  6600, 12233, 12890,  6059,  2203, 14410, 10601,
       13470, 13470,  8334, 11658, 13844,  6799,  7160, 13470,  2020,
       11658,  1837, 13143, 42983,  3987, 12233, 13047, 12233, 10594,
        1708, 36837, 13470, 24106,  9447, 13470,  9101,  6551, 48517,
       44641, 37607,  8334, 30942, 13470, 36837, 10601,  2913, 12592,
       13470, 13470, 12495, 10601, 12629, 13470, 12233, 32108,  1708,
        2913, 26018, 36580,  7160, 13470, 11743,  8334, 37607, 12592,
       47269,  8334,  4673, 37607, 39611,  7441,  7160, 26018,  7441,
        9101,  9447, 36837, 17128,  7345,  8615, 47269,  8334, 13470,
       13470,  2913, 12495, 13470, 12629, 14410, 14394, 37465, 13470,
       39611, 10601, 13470, 39611,  1708, 37607,  1633,  9850,  6238,
       13470, 10736,  7441, 13470, 13470, 13470, 14394,  8334,  7160,
       15828,  7345, 47291,  7441, 13470,  2020, 13470, 32108, 36837,
        7160, 36837,  7348,  7160, 13470, 30184, 13616, 49577, 13470,
        2913,  6238, 32108, 13470,  7160,  2203, 39611, 36837, 36837,
        7348,  8334, 10601, 14001, 13470, 12629,  8965, 39611, 24915,
       13470,  7348, 12233, 39611,  2203,  7160, 36837, 14449, 12032,
       39611, 37465, 13143,  7147,  4433,  8334,  2203,  9101, 37607,
        7147, 13470,  6238,  8334,  9101, 12629,  2203,  8538,  2203,
       16450, 47269, 12233,  7441, 10096,  8334,  4686,  6985, 39611,
       11658, 36580, 13143, 14235,  6238, 36837, 13470, 13887,  2395,
       37607, 13470, 13470, 11658,  5757,  7441, 36837,  1137,  2730,
        4673, 12233, 11743, 15828,  1242, 12629, 32108, 26018, 12495,
       36910, 30942,  1826, 32108,  2020,  7243, 37607, 10601,  9850,
        4296,  4673,  4433,  3597,  8334, 10601, 13844, 26926, 47269,
       14590, 13844, 37607,  4673, 36837, 13047, 39611,  1708,  1633,
       13470,  6985,  7441, 11658,  7348, 11090,  6600,  6238,  9487,
       15828, 10096,  4673, 13470,  8605, 13470, 39611, 13224, 26018,
        4673, 12592,  2020, 11090,  7147, 47269, 36837, 14394,  5757,
       32108, 45863, 13470,  9487,  1708,  9447, 13143,  8334,  7147,
        6238, 12495, 12032, 12629, 39611, 12233, 12233, 18608, 13224,
       13470, 47269,  2395, 11743, 14001, 13470,  1633, 13470, 12233,
       13470,  6985, 11090,  3994, 37607, 13470, 11842, 19496, 39611,
       10096, 14394, 12629,  7348, 12629,  7160, 39611,  8605,  1633,
       13470,  6059, 13143,  8334,  7160,  2395, 21595,  4296,  1633,
        9850,  8334, 11658,  9850,  1826, 13470, 13224, 37465,  7731,
        4673, 11033, 13143, 49577, 32108,  2020,  4673,  4673, 12495,
        8334,  5615,  2217,  7147, 11743,  9447, 10601, 10602, 13470,
       13224, 10602, 37607,  8823,  1632, 12485, 11743, 13470, 13470,
       48517, 24915, 39611, 37607,  9850, 14394, 37607,  9487,  9101,
       47269, 13844,  7731,  8334, 36837,  2020])

In [143]:
from sklearn.tree import DecisionTreeClassifier

In [144]:
model2=DecisionTreeClassifier()

In [145]:
model2.fit(x_train, y_train)

DecisionTreeClassifier()

In [146]:
prediction2 = model2.predict(x_test)

In [147]:
prediction2 = model2.predict(x_test)

In [148]:
prediction2

array([11090,  4762,  4738,  5209, 19964,  4320,  6406, 15612,  6796,
       12557, 37742,  4337, 39722,  3847, 45710,  1515,  4564,  1964,
        5116,  6203, 17081, 24513, 10115, 10325, 23082, 24873, 25992,
       34303,  2304,  1252, 13887, 19719, 10704,  5312, 11436, 43943,
       22493, 23241,  4441, 35491, 17663,  2719, 18310, 12244,  2457,
        7624,  3481,  9788, 43896, 38511,  9411,  9866,  8965, 10197,
        1634, 42211, 15555,  9880, 38746, 45702, 14313, 13887,  4350,
       10381, 26109,  3757,  2566, 11552,  7144,  9625,  5438,  7441,
        3171, 13204, 37133, 16138, 28923,  7749,  3693,  9487,  3171,
        1631,  5699,  3861,  9504, 14007,  7345, 16085,  1837,  9704,
        9282,  3238,  2103, 11879, 17904, 12363,  8347,  1969, 10106,
       16586, 13063,  9991, 17081,  7445,  6940,  4137,  5245, 13462,
        1842,  7640,  9991,  4076,  4889,  5662, 13228,  7789,  6877,
       10106,  6593, 39241, 39983,  1708,  2045,  5267,  3180, 15555,
        8457,  8930,  4661, 45710, 41097, 29330,  1875,  9866, 40003,
       20709,  1837,  5354, 18033, 13770, 16586,  7046, 12224, 42111,
        9377, 16420,  8551,  6196, 13415,  8410,  6686, 11658, 11365,
       13352,  9249, 12044,  4237, 21472, 24915, 28287, 12495, 21098,
       38126, 47462,  7650,  8027, 13607,  6877, 10797,  9140,  3561,
       42211, 21223,  6250,  3943,  2128,  2974, 48675,  7626,  4906,
        3500,  6753, 13204, 35595, 43896,  9620, 37079,  4883,  4058,
       10214, 11763,  4237,  8269,  1984,  5312,  2261, 11944, 14418,
       48885,  5836, 20878,  9361, 23065,  3861,  9304,  8083,  3238,
       29141,  1711, 35069, 14571,  3987, 13390,  7133, 11454, 11353,
        2104, 18955,  5385, 19798, 31620, 38709,  9101, 22395, 28287,
       20296, 37701,  4719,  5116,  3353,  1815, 10594,  4260,  6184,
        5662,  8569, 28340, 11356, 28923,  5649, 11073, 25333,  1705,
        2597, 26018, 10702,  5488,  7448, 28868, 20878,  4237, 10977,
       44260, 43254,  2639, 39774, 17352, 10959,  4747,  4753,  9630,
       23306, 13725, 34672,  4915,  7633,  7726, 38998, 20709,  8083,
        8125,  4234,  7201,  8569, 11345, 10435, 25517,  4561,  7448,
        1917, 12981,  6289,  2927,  3268,  4320,  1631, 10436,  5472,
        9778,  4428, 10959,  3704,  7371,  3206, 24873,  3645, 18806,
        5926,  8240, 47305,  8062,  2483,  2020,  2527, 27375,  1121,
        5373,  3172,  7050,  5373, 16577, 24869, 14451, 49577,  4399,
       11884,  4931, 29186,  6948,  6338,  2200, 23082,  2154,  2155,
       20630,  4500,  8026,  6933,  8556,  8428,  9222,  1532,  7345,
        9778,  8280, 11454,  2130,  2211,  6082, 34166,  9991, 12957,
        1391, 37165, 42303,  5969, 19442,  8765, 11272, 11741, 43753,
        2680,  5240,  6571, 20149, 24180, 11833,  2404,  7209,  2457,
       16450, 32787, 26236,  8968, 11741, 20709,  4266, 10600, 35585,
       11931, 10702, 27218, 12646,  4934,  5662, 41676, 14474,  1621,
        3309, 13063,  3171, 12222,  3213, 11264, 51194,  1725,  3393,
        2709, 12044, 11554, 11299,  1731,  9855,  6858,  3056,  8219,
       10928, 24667,  1986,  6710,  3056, 18765,  5148, 14210,  8277,
        4189,  2709,  5425,  3443,  9290,  9174, 40974, 21195, 48673,
       13430,  8280, 18648,  3471, 17081, 14394, 33475,  2250,  1646,
        2117, 10264,  6849, 11286,  8280, 12648,  7256,  3847, 46889,
        5926, 11741,  2710,  7371, 25382, 11576, 42112, 10704,  4466,
        3392,  7682,  2026, 11856, 11362, 39725, 38282, 13937,  3171,
       10370,  2850,  4149, 13725, 15518, 10797,  9957, 22331,  9377,
        5002, 12643, 10577, 23244,  1135, 12233, 13041, 22478, 12925,
        2352,  5125,  1702, 12142,  9193,  9058,  1727, 10579, 11837,
        3947,  7985, 12235,  2855,  6128,  5699, 12638,  6334, 39722,
       10096,  8627, 27808, 20630, 25678,  9563,  2927, 18767, 36149,
        8083,  5934,  8688, 16138,  8978,  4518, 21595,  8596,  1646,
       13822, 28468,  5458, 52590,  1824, 11538, 11305, 37165,  7153,
        3392,  4719, 11938, 49577,  6402,  3056,  4449, 38711,  8017,
        6664,  7512, 12890,  3260, 11735,  9447,  7419, 10601, 48675,
       23887,  8798,  6079, 10118,  1769, 10325, 12557,  4779,  2527,
       21771,  5031,  1137,  6128,  9850, 19964, 15359, 13725,  4766,
       20009, 21774, 33471,  9722, 16232,  1880])

In [149]:
from sklearn.ensemble import RandomForestClassifier

In [150]:
model3 = RandomForestClassifier()

In [151]:
model3.fit(x_train, y_train)

RandomForestClassifier()

In [152]:
prediction3 = model3.predict(x_test)

In [153]:
prediction3

array([11090,  4762,  4738,  5209, 19798,  4518,  6406, 15612,  6796,
       11946, 37742,  4337, 33750, 20177, 13974,  1515,  4564,  1964,
       15006,  6203, 17081, 24513, 10115, 12485, 36898, 10156, 25992,
       34303,  2304,  1252, 13887, 19719,  6313,  3981, 11436, 43943,
       22493, 23241,  4441, 35491, 17663,  2719, 18310, 12244,  2457,
        7624,  3481,  9788, 43896, 38511,  9411,  9866,  8965, 10197,
        1634, 42211, 14410,  9880, 38746, 45702, 14313, 13887,  4350,
       10381, 26109,  3757,  2566, 11552,  7144,  9625,  5438,  7441,
        3171, 13204, 37133, 14571, 28923,  7749,  3693,  9487,  3062,
        1631,  1826,  3861,  9504, 14007, 26392, 16085,  1837,  9704,
        9282,  3238,  2103, 11879, 17904, 12363,  8347,  1969,  9282,
        1906,  8083,  9991, 17081,  7445,  6940,  4137,  5245, 13462,
        1842,  7640,  9991,  4076,  4889,  1759, 13228,  7789,  7173,
        9282,  6593, 39241, 39983,  1708,  2045,  5267,  3180, 14410,
        8457,  8930,  4661, 13974, 41097, 29330,  1875,  9866, 40003,
       20709,  1837,  5354, 18033, 13770,  1906,  7046, 12224, 42111,
       21232, 16420,  8551,  6196, 13415,  8410,  6686, 11658, 11365,
       13352,  9249,  9861,  4243, 21472, 24915, 48517, 12495, 21098,
       38126, 47462,  7650,  8027, 13607,  7173, 10797,  9140,  3561,
       42211, 21223,  6250,  3943,  2128,  2974, 45863,  7626,  4906,
        3500,  6753, 13204, 35595, 43896,  9620, 37079,  4883,  4058,
       10214, 11763,  4243,  8269,  1984,  3981,  2261, 11944, 14418,
       48885,  5836,  7639,  9361, 23065,  3861,  9304,  8083,  3238,
       29141,  1711, 35069, 14571,  3987, 13390,  7133, 11837, 11353,
        2104, 18955,  5385, 19798, 31620, 38709,  9101, 22395, 48517,
       20296, 37701,  4719, 15006,  3353,  1815, 10594,  4260,  6184,
        5662,  8569, 28340, 11356, 28923,  5649, 11073, 25333,  1705,
        2597, 26018,  8059,  5488,  9541, 28868,  7639,  4237, 10977,
       44260, 43254,  2639, 39774, 17352,  8068,  4747,  4753,  9630,
       23306, 13725, 34672,  4915,  7633,  7726, 38998, 20709,  8083,
        8125,  4234,  7201,  8569, 11345, 10435, 25517,  4561,  9541,
        1917, 12981,  6289,  2927,  3268,  4518,  1631, 10436,  5472,
       19964,  4428,  8068,  3704,  7345,  3206, 10156,  3645, 18806,
        6414,  8240, 47305,  8062,  2483,  2020,  2585, 27375,  1121,
        6849,  3172,  7050,  6849, 16577, 24869, 14451, 49577,  4399,
       11884,  4931, 29186,  6948,  6338,  2200, 36898,  2154,  2155,
        9634,  4500,  8026,  6933,  8556,  8428,  9222,  1532, 26392,
       19964,  8280, 11837,  2130,  2211,  6082, 34166,  9991, 12957,
        1391, 37165, 42303,  5969, 19442,  8765, 11272, 11741, 43753,
        2680,  5240,  6571, 20149, 24180, 11833,  2404,  7209,  2457,
       16450, 32787, 26236,  8968,  5926, 20709,  4266, 10600, 35585,
       11931,  8059, 27218, 12646,  4934,  1759, 41676, 14474,  1621,
        3309,  8083,  3171, 12222,  3213, 11264, 51194,  1725,  3393,
        2709,  9861, 11554, 11299,  1731,  9855,  6858,  3056,  8219,
       10928, 24667,  1986,  6710,  1880, 18765,  5148, 14210,  8277,
        4189,  2709,  5425,  3443,  9290,  9174, 40974, 21195, 48673,
       13430,  8280, 18648,  3471, 17081, 14394, 33475,  2250,  2136,
        2117, 10264,  6849, 11286,  8280, 12648,  7256, 20177, 46889,
        6414,  5926,  2710,  7345, 25382, 11576, 42112,  6313,  4466,
        3392,  7682,  2026, 11856, 11362, 39725, 38282, 13937,  3062,
       10370,  2850,  4149,  6117, 15518, 10797,  9957, 22331, 21232,
        5002, 12643, 10577, 23244,  1135, 12233, 13041, 22478, 12925,
        2352,  5125,  1702, 12142,  9193,  9058,  1727, 10579, 11837,
        3947,  7985, 12235,  2855,  5377,  1826, 12638,  6334, 33750,
       10096,  8627, 27808,  9634, 25678,  9563,  2927, 18767, 36149,
        8083,  5934,  8688, 14571,  8978,  4518, 21595,  8596,  2136,
       13822, 28468,  5458, 52590,  1824, 11538, 11305, 37165,  7153,
        3392,  4719, 11938, 49577,  6402,  1880,  4449, 38711,  8017,
        6664,  7512, 12890,  3260, 11735,  9447,  7419, 10601, 45863,
       23887,  8798,  6079, 10118,  1769, 12485, 11946,  4779,  2585,
       21771,  5031,  1137,  5377,  9850, 19798, 15359,  6117,  4766,
       20009, 21774, 33471,  9722, 16232,  1880])

In [154]:
from sklearn.cluster import KMeans

In [155]:
model4 = KMeans(n_clusters=3, random_state=42, n_init='auto')

In [156]:
model4.fit(x_train,y_train)

KMeans(n_clusters=3, random_state=42)

In [157]:
prediction4 = model4.predict(x_test)

In [158]:
prediction4

array([1, 2, 0, 0, 2, 2, 2, 1, 2, 1, 2, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 1,
       2, 1, 0, 1, 1, 0, 0, 0, 1, 2, 1, 0, 1, 2, 0, 0, 0, 2, 0, 0, 0, 1,
       0, 2, 0, 2, 2, 0, 2, 1, 2, 1, 0, 2, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 2, 1, 2, 2, 0, 1, 0, 0, 1, 2, 0, 1, 0, 0, 2, 0, 1, 1, 2, 1,
       0, 2, 1, 0, 0, 1, 2, 1, 2, 0, 1, 0, 1, 1, 0, 2, 2, 0, 2, 1, 0, 2,
       1, 2, 2, 2, 1, 1, 2, 1, 2, 0, 2, 0, 0, 2, 0, 1, 1, 2, 0, 1, 1, 1,
       0, 1, 2, 1, 0, 2, 0, 1, 0, 2, 1, 2, 1, 0, 2, 2, 1, 2, 2, 1, 1, 1,
       1, 1, 2, 2, 2, 1, 1, 2, 0, 1, 2, 2, 1, 2, 1, 1, 0, 2, 2, 2, 0, 0,
       0, 1, 2, 0, 0, 2, 1, 0, 2, 2, 2, 2, 0, 1, 1, 2, 2, 0, 0, 0, 1, 1,
       2, 2, 2, 1, 2, 0, 1, 1, 0, 1, 0, 2, 0, 0, 1, 2, 1, 1, 0, 0, 2, 2,
       1, 2, 2, 0, 1, 2, 2, 0, 0, 0, 0, 1, 0, 2, 2, 1, 2, 1, 1, 2, 1, 1,
       0, 0, 0, 1, 2, 1, 1, 2, 0, 1, 1, 1, 0, 2, 0, 1, 2, 0, 1, 1, 2, 0,
       0, 2, 2, 2, 1, 1, 1, 0, 2, 1, 1, 1, 1, 0, 1, 0, 1, 2, 0, 0, 2, 0,
       1, 2, 2, 0, 1, 2, 2, 0, 1, 0, 2, 2, 2, 1, 2, 0, 0, 0, 2, 0, 2, 0,
       2, 2, 0, 1, 1, 1, 2, 0, 0, 1, 2, 2, 0, 0, 0, 0, 1, 2, 2, 2, 2, 2,
       2, 0, 2, 2, 2, 1, 0, 0, 2, 0, 1, 1, 0, 0, 1, 2, 0, 1, 0, 1, 2, 0,
       2, 2, 2, 2, 1, 0, 2, 0, 0, 2, 2, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       2, 2, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 2, 0, 2,
       1, 1, 0, 2, 0, 0, 2, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 2, 1, 2, 1, 2, 0, 1, 2, 1, 0, 2, 1, 1, 0, 1,
       0, 0, 2, 0, 1, 1, 2, 2, 1, 0, 1, 0, 0, 2, 0, 1, 1, 2, 1, 2, 1, 1,
       1, 0, 1, 1, 2, 1, 0, 2, 0, 1, 2, 1, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1,
       2, 0, 2, 2, 1, 1, 1, 1, 0, 2, 0, 1, 2, 1, 0, 1, 2, 0, 2, 0, 1, 1,
       2, 1, 0, 1, 1, 0, 2, 0, 0, 1, 1, 2, 0, 0, 0, 2, 2, 2, 0, 0, 1, 2,
       2, 1, 1, 1, 1, 2, 1, 0, 1, 1, 2, 0, 2, 0, 0, 2, 1, 2, 0, 2, 2, 2,
       2, 1, 1, 0, 0], dtype=int32)